[package]
name = "dungeons_plugin"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug = ["colored", "bevy-inspector-egui"]

[dependencies]
bevy = "0.16.1"

bevy-inspector-egui = { version = "0.33.1", optional = true}
rand = "0.9.2"

colored = { version = "3.0.0", optional = true }
